# Disable blank issues
blank_issues_enabled: false

## Custom contact links shown when creating a new issue
contact_links:
  - name: GitHub Support
    url: https://support.github.com/contact
    about: Contact Support if you're having trouble with your GitHub account.
